apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: mrrfifa/soccer-club-server
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: "3001"
            - name: MDB_CONNECT
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: database_url
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: jwt_secret
            - name: CLIENT_API_URL
              valueFrom:
                configMapKeyRef:
                  name: frontend-configmap
                  key: origin1
            - name: ADMIN_API_URL
              valueFrom:
                configMapKeyRef:
                  name: frontend-configmap
                  key: origin2
            - name: CLIENT_PORT
              valueFrom:
                configMapKeyRef:
                  name: frontend-configmap
                  key: port1
            - name: ADMIN_PORT
              valueFrom:
                configMapKeyRef:
                  name: frontend-configmap
                  key: port2
            
          # resources:
          #   requests:
          #     cpu: "100m"
          #     memory: "100Mi"
          #   limits:
          #     cpu: "500m"
          #     memory: "500Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
