apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque                 
data:
  #credentials must be base64 encoded 
  mongo-root-username: cm9vdA== #username in base64
  mongo-root-password: cGFzc3dvcmQ= #password in base64
  jwt_secret: NzAxNGUwMTA1YmQ4ZTM4N2FkMzc0Y2U4YjhjNTQyYmMyYTYxY2QxZjUyYWRlNDlkZmI0MWJjMGM0ZjEyNDQzZA== #random jwt secret in base64
  database_url: bW9uZ29kYjovL3Jvb3Q6cGFzc3dvcmRAbW9uZ29kYjoyNzAxNy9teS1kYj9hdXRoU291cmNlPWFkbWlu # connection string in base64